# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c8c000af134fba3584c954107514b12b1584c5982e2f41c972ab526939275453188435496d0cfe2eba674b16d09cab2546b4a96fe4d2db983b1e229723798d9

test:
  secret_key_base: ce055ac1190105c22d3211f3c2a598051c9b5e2190e3899ef79093b49de6d7665d27efb454b7d389e3bf9d959198fed7cdeadb94ec53b0b058c2058fde315cfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
